### PR TITLE
Main page app mobile created.

### PR DESCRIPTION
**Pull request by chicca1210**

### CODE REVIEW

**Comment by cach92** [comment]
Please change the name of the Pull Request with a more meaningful name (I don't know if this is the main page of desktop app or mobil app)

**Comment by cach92** [comment]
Or, in alternative, add a description

**Comment by ashleycaselli** [comment]
[(10) Realizzazione GUI Mobile di Base (Cordova) [10]](https://trello.com/c/mXroJwb8/68-10-realizzazione-gui-mobile-di-base-cordova-10)

**Comment by chicca1210** [comment]
[(10) Realizzazione Prima Parte GUI Mobile di Base (Cordova) [10]](https://trello.com/c/mXroJwb8/68-10-realizzazione-prima-parte-gui-mobile-di-base-cordova-10)

**Pull request merged**
